version: "3.7"

services:
  database_api_rest:
    image: postgres
    container_name: crypto
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local